import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";
import Signin from "@/components/Signin";
import Footer from '@/components/Footer';
import Main from '@/components/Main';
import { ReactNode } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <Navigation />
      <Main/>
      <Footer/>
      {children}
    </>
  );
}

export function SimpleLayout({ children }: { children: ReactNode }) {
  return (
    <>
      {children}
    </>
  );
}
